// <auto-generated />
using System;
using CoreAxis.Modules.DynamicForm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreAxis.Modules.DynamicForm.Infrastructure.Migrations
{
    [DbContext(typeof(DynamicFormDbContext))]
    partial class DynamicFormDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dynamicform")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CacheTtlSeconds")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceName", "EndpointName")
                        .HasDatabaseName("IX_DataSource_Service_Endpoint");

                    b.ToTable("DataSources", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMultiStep")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_Forms_CreatedOn");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("IX_Forms_IsPublished");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Forms_Name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Forms_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Forms_TenantId_Name_Unique");

                    b.ToTable("Forms", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("IX_FormAccessPolicies_EffectiveFrom");

                    b.HasIndex("EffectiveTo")
                        .HasDatabaseName("IX_FormAccessPolicies_EffectiveTo");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormAccessPolicies_FormId");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_FormAccessPolicies_IsEnabled");

                    b.HasIndex("PolicyType")
                        .HasDatabaseName("IX_FormAccessPolicies_PolicyType");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_FormAccessPolicies_Priority");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("IX_FormAccessPolicies_TargetId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormAccessPolicies_TenantId");

                    b.HasIndex("FormId", "PolicyType", "TargetId")
                        .HasDatabaseName("IX_FormAccessPolicies_FormId_PolicyType_TargetId");

                    b.HasIndex("TenantId", "FormId", "Priority")
                        .HasDatabaseName("IX_FormAccessPolicies_TenantId_FormId_Priority");

                    b.ToTable("FormAccessPolicies", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Information");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_FormAuditLogs_Action");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_FormAuditLogs_Category");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_FormAuditLogs_CorrelationId");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_FormAuditLogs_EntityId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_FormAuditLogs_EntityType");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormAuditLogs_FormId");

                    b.HasIndex("FormSubmissionId")
                        .HasDatabaseName("IX_FormAuditLogs_FormSubmissionId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_FormAuditLogs_SessionId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_FormAuditLogs_Severity");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormAuditLogs_TenantId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_FormAuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FormAuditLogs_UserId");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("IX_FormAuditLogs_TenantId_Timestamp");

                    b.HasIndex("EntityType", "EntityId", "Timestamp")
                        .HasDatabaseName("IX_FormAuditLogs_EntityType_EntityId_Timestamp");

                    b.HasIndex("UserId", "Action", "Timestamp")
                        .HasDatabaseName("IX_FormAuditLogs_UserId_Action_Timestamp");

                    b.ToTable("FormAuditLogs", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalculationExpression")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConditionalLogic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CssClasses")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HelpText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldType")
                        .HasDatabaseName("IX_FormFields_FieldType");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormFields_FormId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FormFields_Name");

                    b.HasIndex("Order")
                        .HasDatabaseName("IX_FormFields_Order");

                    b.HasIndex("FormId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_FormFields_FormId_Name_Unique");

                    b.HasIndex("FormId", "Order")
                        .HasDatabaseName("IX_FormFields_FormId_Order");

                    b.ToTable("FormFields", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanSkip")
                        .HasColumnType("bit");

                    b.Property<string>("ConditionalLogic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DependsOnSteps")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRepeatable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSkippable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinTimeSeconds")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Standard");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_FormSteps_CreatedOn");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormSteps_FormId");

                    b.HasIndex("IsRequired")
                        .HasDatabaseName("IX_FormSteps_IsRequired");

                    b.HasIndex("IsSkippable")
                        .HasDatabaseName("IX_FormSteps_IsSkippable");

                    b.HasIndex("StepNumber")
                        .HasDatabaseName("IX_FormSteps_StepNumber");

                    b.HasIndex("StepType")
                        .HasDatabaseName("IX_FormSteps_StepType");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormSteps_TenantId");

                    b.HasIndex("FormId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FormSteps_FormId_StepNumber_Unique");

                    b.HasIndex("FormId", "IsActive", "StepNumber")
                        .HasDatabaseName("IX_FormSteps_FormId_IsActive_StepNumber");

                    b.HasIndex("TenantId", "FormId", "IsActive")
                        .HasDatabaseName("IX_FormSteps_TenantId_FormId_IsActive");

                    b.HasIndex("TenantId", "StepType", "IsActive")
                        .HasDatabaseName("IX_FormSteps_TenantId_StepType_IsActive");

                    b.ToTable("FormSteps", "dynamicform", t =>
                        {
                            t.HasCheckConstraint("CK_FormSteps_MaxAttempts", "[MaxAttempts] > 0");

                            t.HasCheckConstraint("CK_FormSteps_StepNumber", "[StepNumber] > 0");

                            t.HasCheckConstraint("CK_FormSteps_TimeoutMinutes", "[TimeoutMinutes] IS NULL OR [TimeoutMinutes] > 0");
                        });
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStepSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NotStarted");

                    b.Property<string>("StepData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TimeSpentSeconds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_FormStepSubmissions_CompletedAt");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_FormStepSubmissions_CreatedOn");

                    b.HasIndex("FormStepId")
                        .HasDatabaseName("IX_FormStepSubmissions_FormStepId");

                    b.HasIndex("FormSubmissionId")
                        .HasDatabaseName("IX_FormStepSubmissions_FormSubmissionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_FormStepSubmissions_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FormStepSubmissions_Status");

                    b.HasIndex("StepNumber")
                        .HasDatabaseName("IX_FormStepSubmissions_StepNumber");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormStepSubmissions_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FormStepSubmissions_UserId");

                    b.HasIndex("FormSubmissionId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FormStepSubmissions_FormSubmissionId_StepNumber_Unique");

                    b.HasIndex("FormSubmissionId", "Status", "StepNumber")
                        .HasDatabaseName("IX_FormStepSubmissions_FormSubmissionId_Status_StepNumber");

                    b.HasIndex("TenantId", "FormSubmissionId", "Status")
                        .HasDatabaseName("IX_FormStepSubmissions_TenantId_FormSubmissionId_Status");

                    b.HasIndex("TenantId", "UserId", "Status")
                        .HasDatabaseName("IX_FormStepSubmissions_TenantId_UserId_Status");

                    b.ToTable("FormStepSubmissions", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMultiStep")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referrer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("SubmittedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormSubmissions_FormId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FormSubmissions_Status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("IX_FormSubmissions_SubmittedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormSubmissions_TenantId");

                    b.HasIndex("TenantId", "FormId", "SubmittedAt")
                        .HasDatabaseName("IX_FormSubmissions_TenantId_FormId_SubmittedAt");

                    b.ToTable("FormSubmissions", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormVersions_FormId");

                    b.HasIndex("IsCurrent")
                        .HasDatabaseName("IX_FormVersions_IsCurrent");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("IX_FormVersions_IsPublished");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("IX_FormVersions_PublishedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormVersions_TenantId");

                    b.HasIndex("Version")
                        .HasDatabaseName("IX_FormVersions_Version");

                    b.HasIndex("FormId", "IsCurrent")
                        .HasDatabaseName("IX_FormVersions_FormId_IsCurrent")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("FormId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_FormVersions_FormId_Version_Unique");

                    b.ToTable("FormVersions", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceMetrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_FormulaDefinitions_Category");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("IX_FormulaDefinitions_IsPublished");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FormulaDefinitions_Name");

                    b.HasIndex("ReturnType")
                        .HasDatabaseName("IX_FormulaDefinitions_ReturnType");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormulaDefinitions_TenantId");

                    b.HasIndex("Version")
                        .HasDatabaseName("IX_FormulaDefinitions_Version");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_FormulaDefinitions_TenantId_Name_Unique");

                    b.HasIndex("TenantId", "Category", "IsPublished")
                        .HasDatabaseName("IX_FormulaDefinitions_TenantId_Category_IsPublished");

                    b.ToTable("FormulaDefinitions", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaEvaluationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ContextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EvaluationContext")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EvaluationMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ExecutionTimeMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormulaDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormulaVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemoryUsageBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_CompletedAt");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_CorrelationId");

                    b.HasIndex("EvaluationContext")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_EvaluationContext");

                    b.HasIndex("ExecutionTimeMs")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_ExecutionTimeMs");

                    b.HasIndex("FormId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_FormId");

                    b.HasIndex("FormSubmissionId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_FormSubmissionId");

                    b.HasIndex("FormulaDefinitionId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_FormulaDefinitionId");

                    b.HasIndex("FormulaVersionId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_SessionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_UserId");

                    b.HasIndex("TenantId", "StartedAt")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_TenantId_StartedAt");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_UserId_StartedAt");

                    b.HasIndex("FormulaDefinitionId", "Status", "StartedAt")
                        .HasDatabaseName("IX_FormulaEvaluationLogs_FormulaDefinitionId_Status_StartedAt");

                    b.ToTable("FormulaEvaluationLogs", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageExecutionTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<string>("ChangeLog")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dependencies")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormulaDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ValidationRules")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormulaDefinitionId")
                        .HasDatabaseName("IX_FormulaVersions_FormulaDefinitionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FormulaVersions_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("IX_FormulaVersions_IsPublished")
                        .HasFilter("[IsPublished] = 1");

                    b.HasIndex("LastExecutedAt")
                        .HasDatabaseName("IX_FormulaVersions_LastExecutedAt");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("IX_FormulaVersions_PublishedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FormulaVersions_TenantId");

                    b.HasIndex("FormulaDefinitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FormulaVersions_FormulaDefinitionId_VersionNumber");

                    b.HasIndex("FormulaDefinitionId", "IsActive", "VersionNumber")
                        .HasDatabaseName("IX_FormulaVersions_FormulaDefinitionId_IsActive_VersionNumber");

                    b.HasIndex("TenantId", "FormulaDefinitionId", "IsActive")
                        .HasDatabaseName("IX_FormulaVersions_TenantId_FormulaDefinitionId_IsActive");

                    b.HasIndex("TenantId", "IsPublished", "PublishedAt")
                        .HasDatabaseName("IX_FormulaVersions_TenantId_IsPublished_PublishedAt");

                    b.HasIndex("FormulaDefinitionId", "IsPublished", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_FormulaVersions_Published_EffectiveWindow");

                    b.ToTable("FormulaVersions", "DynamicForm", t =>
                        {
                            t.HasCheckConstraint("CK_FormulaVersions_ActiveConstraint", "([IsActive] = 0) OR ([IsActive] = 1 AND [IsPublished] = 1)");

                            t.HasCheckConstraint("CK_FormulaVersions_AverageExecutionTime", "[AverageExecutionTime] IS NULL OR [AverageExecutionTime] >= 0");

                            t.HasCheckConstraint("CK_FormulaVersions_EffectiveRange", "([EffectiveFrom] IS NULL) OR ([EffectiveTo] IS NULL) OR ([EffectiveFrom] <= [EffectiveTo])");

                            t.HasCheckConstraint("CK_FormulaVersions_ExecutionCount", "[ExecutionCount] >= 0");

                            t.HasCheckConstraint("CK_FormulaVersions_PublishedConstraint", "([IsPublished] = 0) OR ([IsPublished] = 1 AND [PublishedAt] IS NOT NULL AND [PublishedBy] IS NOT NULL)");

                            t.HasCheckConstraint("CK_FormulaVersions_VersionNumber", "[VersionNumber] > 0");
                        });
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.ProductFormulaBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormulaDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormulaDefinitionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormulaDefinitionId");

                    b.HasIndex("FormulaDefinitionId1");

                    b.HasIndex("ProductId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductFormulaBinding_ProductId_Version");

                    b.ToTable("ProductFormulaBindings", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Consumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalDataSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PricingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Consumed")
                        .HasDatabaseName("IX_Quote_Consumed");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Quote_ExpiresAt");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Quote_ProductId");

                    b.HasIndex("ProductId", "Consumed", "ExpiresAt")
                        .HasDatabaseName("IX_Quote_Product_Consumed_Expires");

                    b.ToTable("Quotes", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_OutboxMessages_NextRetryAt");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_OccurredOn");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedOn");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_OutboxMessages_Type");

                    b.HasIndex("ProcessedOn", "NextRetryAt")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedOn_NextRetryAt")
                        .HasFilter("[ProcessedOn] IS NULL");

                    b.HasIndex("TenantId", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_TenantId_OccurredOn");

                    b.ToTable("OutboxMessages", "dynamicform");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormAccessPolicy", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormAuditLog", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", "FormSubmission")
                        .WithMany()
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Form");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormField", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStep", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany("Steps")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStepSubmission", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStep", "FormStep")
                        .WithMany("Submissions")
                        .HasForeignKey("FormStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", "FormSubmission")
                        .WithMany("StepSubmissions")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormStep");

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany("Submissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormVersion", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany("Versions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaEvaluationLog", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", "FormSubmission")
                        .WithMany()
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", "FormulaDefinition")
                        .WithMany("EvaluationLogs")
                        .HasForeignKey("FormulaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaVersion", "FormulaVersion")
                        .WithMany("EvaluationLogs")
                        .HasForeignKey("FormulaVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Form");

                    b.Navigation("FormSubmission");

                    b.Navigation("FormulaDefinition");

                    b.Navigation("FormulaVersion");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaVersion", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", "FormulaDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("FormulaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormulaDefinition");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.ProductFormulaBinding", b =>
                {
                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", null)
                        .WithMany()
                        .HasForeignKey("FormulaDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", "FormulaDefinition")
                        .WithMany()
                        .HasForeignKey("FormulaDefinitionId1");

                    b.Navigation("FormulaDefinition");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.Form", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Steps");

                    b.Navigation("Submissions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormStep", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormSubmission", b =>
                {
                    b.Navigation("StepSubmissions");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaDefinition", b =>
                {
                    b.Navigation("EvaluationLogs");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CoreAxis.Modules.DynamicForm.Domain.Entities.FormulaVersion", b =>
                {
                    b.Navigation("EvaluationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
